// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetCachePath():Promise<string>;

export function GetHomeDir():Promise<string>;

export function ListDir(arg1:string):Promise<Array<main.FileNode>>;

export function LoadCache():Promise<main.CacheData>;

export function OpenFileDialog():Promise<string>;

export function OpenFolderDialog():Promise<string>;

export function ReadFile(arg1:string):Promise<string>;

export function SaveCache(arg1:main.CacheData):Promise<void>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;
