// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCachePath() {
  return window['go']['main']['App']['GetCachePath']();
}

export function GetHomeDir() {
  return window['go']['main']['App']['GetHomeDir']();
}

export function ListDir(arg1) {
  return window['go']['main']['App']['ListDir'](arg1);
}

export function LoadCache() {
  return window['go']['main']['App']['LoadCache']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function OpenFolderDialog() {
  return window['go']['main']['App']['OpenFolderDialog']();
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function SaveCache(arg1) {
  return window['go']['main']['App']['SaveCache'](arg1);
}
